//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_PBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Baza_wynajmuEntities : DbContext
    {
        public Baza_wynajmuEntities()
            : base("name=Baza_wynajmuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<DaneMieszkania> DaneMieszkanias { get; set; }
        public virtual DbSet<Klient> Klients { get; set; }
        public virtual DbSet<Wlasciciel> Wlasciciels { get; set; }
        public virtual DbSet<Bilan> Bilans { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Oferta> Ofertas { get; set; }
    }
}
