//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_PBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilan
    {
        public int idB { get; set; }
        public Nullable<int> idM { get; set; }
        public Nullable<System.DateTime> dataTransakcji { get; set; }
        public Nullable<decimal> kwota { get; set; }
        public string kategoria { get; set; }
        public string notka { get; set; }
    
        public virtual DaneMieszkania DaneMieszkania { get; set; }
    }
}
