//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_PBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int idL { get; set; }
        public string email { get; set; }
        public string haslo { get; set; }
        public Nullable<int> idK { get; set; }
        public Nullable<int> idW { get; set; }
        public Nullable<int> idA { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual Klient Klient { get; set; }
        public virtual Wlasciciel Wlasciciel { get; set; }
    }
}
