//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_PBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zainteresowani
    {
        public int idZ { get; set; }
        public Nullable<int> idO { get; set; }
        public Nullable<int> idK { get; set; }
        public string daneKontaktowe { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Oferta Oferta { get; set; }

        public override string ToString()
        {
            return $"{Klient.imie} {Klient.nazwisko}";
        }
    }
}
